### ISSUE TITLE
Create REST API

### ISSUE THREAD

**Issue by sacrael** [rcos/rpi-offcampus-housing#12]
**Endpoints**
Student:
GET /api/students/:id -> retrieve student info with specified student id, or an error if student does not exist.
PUT /api/students -> add new student

Landlord:
GET /api/landlords/:id -> retrieve landlord info with specified id
PUT /api/landlords -> add new landlord data

Property:
GET /api/properties/:id -> retrieve property with specified id
PUT /api/properties -> Create a new property document entry
GET /api/properties/:id/landlord -> Retrieve the landlord that owns this property
GET /api/properties/:id/reviews?limit={limit}&offset={offset} -> Retrieve `limit` reviews for the property with `id`, starting from `offset` entry.

Review
GET /api/reviews/:id -> retrieve review with `id`
PUT /api/reviews -> Create a new review

**Comment by 123joshuawu** [comment]
@sacrael we can split this if you want, probably gonna be a lot of code

**Comment by sacrael** [comment]
Oh, I just finished it up. These gets and puts are fairly similar so I was able to reuse a good amount of the code.
