### ISSUE TITLE
Landlord Login & Registration

### ISSUE THREAD

**Issue by sacrael** [rcos/rpi-offcampus-housing#29]
Implement login and registration for landlords.

Tasks:
- [x] Landlord registration form
- [x] Connect with PUT '/api/landlords' API
- [x] Landlord login form
- [x] Passport local strategy for landlord login
- [x] Store user type in redux state on frontend

**Comment by sacrael** [comment]
Additional:
- [ ] Restrict AuthRouter based on type of logged in user

**Comment by sacrael** [comment]
@123joshuawu I have added a 'password' field to the Landlord schema, which is why I believe the CI test failed on this branch.

**Comment by 123joshuawu** [comment]
I'll update tests
