### ISSUE TITLE
Migrate REST to GraphQL

### ISSUE THREAD

**Issue by sacrael** [rcos/rpi-offcampus-housing#40]
(1) Setup GraphQL backend API.

(2) Create Resolvers and Schemes for Property, Student, Review, Landlord & Institution to replace existing REST endpoints.
- [ ] Landlord Resolvers
- [ ] Institution Resolvers
- [ ] Property Resolvers
- [ ] Review Resolvers
- [ ] Student Resolvers

(3) Update `web/src/api` to connect to graphql endpoint and request typed resources.

(4) Update views that use API endpoints to use typed arguments from promises.

**Comment by 123joshuawu** [comment]
This seems like a promising tutorial: https://blog.logrocket.com/integrating-typescript-graphql/ 

Uses https://typegraphql.com/ for schema definition and resolvers

Also combined with https://github.com/typegoose/typegoose to integrate mongoose schemas with typescript interface declarations which seems neat

Another GraphQL server option is Apollo https://www.apollographql.com/docs/apollo-server/? I've only used their client which was nice, but they also offer a server implementation

I haven't done GraphQL in TypeScript/Express before so I'm open to anything, let me know what you think @sacrael

**Comment by sacrael** [comment]
@123joshuawu 
Just read through the LogRocket tutorial and it looks like what we want. I'm gonna try to set it up this afternoon and test out some queries/resolvers before migrating.
